###### 抛出异常

使用throw抛出任意类型对象。抛出异常后，程序将沿着调用链寻找匹配的catch块。如果在主函数中依然无法匹配catch，调用`terminate()`。

可以在声明处参数列表后加上noexcept指明函数不会抛出异常，编译器将对其进行优化，但如果抛出异常，程序将直接调用`terminate()`。

###### 捕获异常

使用catch(...)可以捕获所有异常，但无法获取具体的异常对象，可放在catch块末尾，表示缺省捕获。

在匹配catch时，最终的匹配结果并不一定是最佳匹配，而是第一个能够匹配的。

在catch块中，可使用空的throw重新抛出捕获的异常。

###### 源码信息

C++20提供类`std::source_location`，提供了更好的方式获取源码信息。

使用`std::source_location:current()`获取调用点的信息对象，通过成员函数`line()`、`column()`、`file_name()`和`function_name()`可获取具体的信息。

```cpp
// loc实际是在调用处完成创建的，而并非log函数内部
auto log(const std::string &msg, std::source_location loc = std::source_location::current())
{
    fmt::print("msg : {} \n", msg);
    fmt::print("at {}:{} {},{}\n", loc.file_name(), loc.function_name(), loc.line(), loc.column());
}
```

###### 静态断言

c++11引入静态断言`static_assert(expr, msg)`表达式，其会在编译期进行断言处理，可以出现在块作用域中的任何位置以及全局作用域中。
